<?php
include '../helper/activate_account_function.php';
include '../helper/function.php';
include '../signup_confirmation/connection/connect.php';

$token = $_POST['token'];
$password = $_POST['password'];

$query = "select * from user_data where email_token = :token";
$pdo = $db->prepare($query);
$pdo->bindValue(':token', $token);
$pdo->execute();
$result = $pdo->fetch();

$passwordhs = password_hash($password, PASSWORD_DEFAULT);

if($result == null){

echo "<script>
        alert('please, check your token');
       </script>";

}else{

$query = "update user_data set password = :password";
 	$pdo = $db->prepare($query);
	$pdo->bindValue(':password', $passwordhs);
	$pdo->execute();

	echo "<script>
        alert('successfully, your password is changed now!');
        location.replace('../user_log_in.php');
       </script>";

}


?>