<?php
include '../signup_confirmation/connection/connect.php';
include '../helper/reset_email_function.php';
include '../helper/activate_account_function.php';

$email = $_POST['email'];

$token = generateRandomString();

$query = "select * from user_data where email = :email";
$pdo = $db->prepare($query);
$pdo->bindValue(':email', $email);
$pdo->execute();
$result = $pdo->fetch();

$queryy = "update user_data set email_token = :token";
 	$pdo = $db->prepare($queryy);
	$pdo->bindValue(':token', $token);
	$pdo->execute();

send_token($token, $email);

if($result == null){
		echo "<script>
		alert('your email was not found..');
		location.replace('../reset_password.php');
		</script>";

    }else{
    	echo "<script>
    	alert('we sent token though your email. check it now!');
        location.replace('../reset_password_change.php');
        </script>";
    }
 ?>
